/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.warehouse.WarehouseModellingRuntimeModule;
import org.xtext.example.warehouse.WarehouseModellingStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WarehouseModellingIdeSetup extends WarehouseModellingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WarehouseModellingRuntimeModule(), new WarehouseModellingIdeModule()));
	}
	
}
