/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.warehouse.ui.internal.WarehouseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WarehouseModellingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(WarehouseActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		WarehouseActivator activator = WarehouseActivator.getInstance();
		return activator != null ? activator.getInjector(WarehouseActivator.ORG_XTEXT_EXAMPLE_WAREHOUSE_WAREHOUSEMODELLING) : null;
	}

}
