/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.warehouse.services.WarehouseModellingGrammarAccess;
import org.xtext.example.warehouse.warehouseModelling.Company;
import org.xtext.example.warehouse.warehouseModelling.Employee;
import org.xtext.example.warehouse.warehouseModelling.Manager;
import org.xtext.example.warehouse.warehouseModelling.Person;
import org.xtext.example.warehouse.warehouseModelling.Team;
import org.xtext.example.warehouse.warehouseModelling.Warehouse;
import org.xtext.example.warehouse.warehouseModelling.WarehouseManagement;
import org.xtext.example.warehouse.warehouseModelling.WarehouseModellingPackage;

@SuppressWarnings("all")
public class WarehouseModellingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private WarehouseModellingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == WarehouseModellingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case WarehouseModellingPackage.COMPANY:
				sequence_Company(context, (Company) semanticObject); 
				return; 
			case WarehouseModellingPackage.EMPLOYEE:
				sequence_Employee(context, (Employee) semanticObject); 
				return; 
			case WarehouseModellingPackage.MANAGER:
				sequence_Manager(context, (Manager) semanticObject); 
				return; 
			case WarehouseModellingPackage.PERSON:
				sequence_Person(context, (Person) semanticObject); 
				return; 
			case WarehouseModellingPackage.TEAM:
				sequence_Team(context, (Team) semanticObject); 
				return; 
			case WarehouseModellingPackage.WAREHOUSE:
				sequence_Warehouse(context, (Warehouse) semanticObject); 
				return; 
			case WarehouseModellingPackage.WAREHOUSE_MANAGEMENT:
				sequence_WarehouseManagement(context, (WarehouseManagement) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Company returns Company
	 *
	 * Constraint:
	 *     (name=ID address=ID warehouses+=Warehouse* teams+=Team*)
	 */
	protected void sequence_Company(ISerializationContext context, Company semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Role returns Employee
	 *     Employee returns Employee
	 *
	 * Constraint:
	 *     (startDate=ID endDate=ID)
	 */
	protected void sequence_Employee(ISerializationContext context, Employee semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.ROLE__START_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.ROLE__START_DATE));
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.ROLE__END_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.ROLE__END_DATE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEmployeeAccess().getStartDateIDTerminalRuleCall_1_0(), semanticObject.getStartDate());
		feeder.accept(grammarAccess.getEmployeeAccess().getEndDateIDTerminalRuleCall_2_0(), semanticObject.getEndDate());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Role returns Manager
	 *     Manager returns Manager
	 *
	 * Constraint:
	 *     (startDate=ID endDate=ID)
	 */
	protected void sequence_Manager(ISerializationContext context, Manager semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.ROLE__START_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.ROLE__START_DATE));
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.ROLE__END_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.ROLE__END_DATE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getManagerAccess().getStartDateIDTerminalRuleCall_1_0(), semanticObject.getStartDate());
		feeder.accept(grammarAccess.getManagerAccess().getEndDateIDTerminalRuleCall_2_0(), semanticObject.getEndDate());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Person returns Person
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Person(ISerializationContext context, Person semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.PERSON__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.PERSON__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Team returns Team
	 *
	 * Constraint:
	 *     id=ID
	 */
	protected void sequence_Team(ISerializationContext context, Team semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WarehouseModellingPackage.Literals.TEAM__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WarehouseModellingPackage.Literals.TEAM__ID));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTeamAccess().getIdIDTerminalRuleCall_1_0(), semanticObject.getId());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     WarehouseManagement returns WarehouseManagement
	 *
	 * Constraint:
	 *     companies+=Company+
	 */
	protected void sequence_WarehouseManagement(ISerializationContext context, WarehouseManagement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Warehouse returns Warehouse
	 *
	 * Constraint:
	 *     (name=ID workers+=Person*)
	 */
	protected void sequence_Warehouse(ISerializationContext context, Warehouse semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
