/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.warehouseModelling;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.warehouse.warehouseModelling.WarehouseModellingPackage#getEmployee()
 * @model
 * @generated
 */
public interface Employee extends Role
{
} // Employee
