/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.warehouseModelling;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.warehouse.warehouseModelling.WarehouseModellingFactory
 * @model kind="package"
 * @generated
 */
public interface WarehouseModellingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "warehouseModelling";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/warehouse/WarehouseModelling";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "warehouseModelling";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WarehouseModellingPackage eINSTANCE = org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl <em>Warehouse Management</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouseManagement()
   * @generated
   */
  int WAREHOUSE_MANAGEMENT = 0;

  /**
   * The feature id for the '<em><b>Companies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_MANAGEMENT__COMPANIES = 0;

  /**
   * The number of structural features of the '<em>Warehouse Management</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_MANAGEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getCompany()
   * @generated
   */
  int COMPANY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__NAME = 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__ADDRESS = 1;

  /**
   * The feature id for the '<em><b>Warehouses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__WAREHOUSES = 2;

  /**
   * The feature id for the '<em><b>Teams</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__TEAMS = 3;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl <em>Warehouse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouse()
   * @generated
   */
  int WAREHOUSE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Workers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__WORKERS = 1;

  /**
   * The number of structural features of the '<em>Warehouse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl <em>Team</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTeam()
   * @generated
   */
  int TEAM = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM__ID = 0;

  /**
   * The number of structural features of the '<em>Team</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getRole()
   * @generated
   */
  int ROLE = 5;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__START_DATE = 0;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__END_DATE = 1;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getEmployee()
   * @generated
   */
  int EMPLOYEE = 6;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__START_DATE = ROLE__START_DATE;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__END_DATE = ROLE__END_DATE;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl <em>Manager</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getManager()
   * @generated
   */
  int MANAGER = 7;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__START_DATE = ROLE__START_DATE;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__END_DATE = ROLE__END_DATE;

  /**
   * The number of structural features of the '<em>Manager</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.WarehouseManagement <em>Warehouse Management</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Warehouse Management</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.WarehouseManagement
   * @generated
   */
  EClass getWarehouseManagement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.WarehouseManagement#getCompanies <em>Companies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Companies</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.WarehouseManagement#getCompanies()
   * @see #getWarehouseManagement()
   * @generated
   */
  EReference getWarehouseManagement_Companies();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company
   * @generated
   */
  EClass getCompany();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Company#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getName()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Company#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getAddress()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Address();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Company#getWarehouses <em>Warehouses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Warehouses</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getWarehouses()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Warehouses();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Company#getTeams <em>Teams</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Teams</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getTeams()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Teams();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse <em>Warehouse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Warehouse</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse
   * @generated
   */
  EClass getWarehouse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse#getName()
   * @see #getWarehouse()
   * @generated
   */
  EAttribute getWarehouse_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse#getWorkers <em>Workers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workers</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse#getWorkers()
   * @see #getWarehouse()
   * @generated
   */
  EReference getWarehouse_Workers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Team <em>Team</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Team</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Team
   * @generated
   */
  EClass getTeam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Team#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Team#getId()
   * @see #getTeam()
   * @generated
   */
  EAttribute getTeam_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Role#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role#getStartDate()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_StartDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Role#getEndDate <em>End Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Date</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role#getEndDate()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_EndDate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Employee
   * @generated
   */
  EClass getEmployee();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Manager <em>Manager</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Manager</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Manager
   * @generated
   */
  EClass getManager();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WarehouseModellingFactory getWarehouseModellingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl <em>Warehouse Management</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouseManagement()
     * @generated
     */
    EClass WAREHOUSE_MANAGEMENT = eINSTANCE.getWarehouseManagement();

    /**
     * The meta object literal for the '<em><b>Companies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE_MANAGEMENT__COMPANIES = eINSTANCE.getWarehouseManagement_Companies();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getCompany()
     * @generated
     */
    EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__NAME = eINSTANCE.getCompany_Name();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__ADDRESS = eINSTANCE.getCompany_Address();

    /**
     * The meta object literal for the '<em><b>Warehouses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__WAREHOUSES = eINSTANCE.getCompany_Warehouses();

    /**
     * The meta object literal for the '<em><b>Teams</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__TEAMS = eINSTANCE.getCompany_Teams();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl <em>Warehouse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouse()
     * @generated
     */
    EClass WAREHOUSE = eINSTANCE.getWarehouse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAREHOUSE__NAME = eINSTANCE.getWarehouse_Name();

    /**
     * The meta object literal for the '<em><b>Workers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE__WORKERS = eINSTANCE.getWarehouse_Workers();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl <em>Team</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTeam()
     * @generated
     */
    EClass TEAM = eINSTANCE.getTeam();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEAM__ID = eINSTANCE.getTeam_Id();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__START_DATE = eINSTANCE.getRole_StartDate();

    /**
     * The meta object literal for the '<em><b>End Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__END_DATE = eINSTANCE.getRole_EndDate();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getEmployee()
     * @generated
     */
    EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl <em>Manager</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getManager()
     * @generated
     */
    EClass MANAGER = eINSTANCE.getManager();

  }

} //WarehouseModellingPackage
