/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.warehouseModelling;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.warehouse.warehouseModelling.WarehouseModellingFactory
 * @model kind="package"
 * @generated
 */
public interface WarehouseModellingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "warehouseModelling";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/warehouse/WarehouseModelling";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "warehouseModelling";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WarehouseModellingPackage eINSTANCE = org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl <em>Warehouse Management</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouseManagement()
   * @generated
   */
  int WAREHOUSE_MANAGEMENT = 0;

  /**
   * The feature id for the '<em><b>Companies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_MANAGEMENT__COMPANIES = 0;

  /**
   * The number of structural features of the '<em>Warehouse Management</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_MANAGEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getCompany()
   * @generated
   */
  int COMPANY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__NAME = 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__ADDRESS = 1;

  /**
   * The feature id for the '<em><b>Warehouses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__WAREHOUSES = 2;

  /**
   * The feature id for the '<em><b>Teams</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__TEAMS = 3;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__TASKS = 4;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl <em>Warehouse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouse()
   * @generated
   */
  int WAREHOUSE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Workers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__WORKERS = 1;

  /**
   * The number of structural features of the '<em>Warehouse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl <em>Team</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTeam()
   * @generated
   */
  int TEAM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM__NAME = 0;

  /**
   * The number of structural features of the '<em>Team</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ROLES = 1;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getRole()
   * @generated
   */
  int ROLE = 5;

  /**
   * The feature id for the '<em><b>Employee Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__EMPLOYEE_ID = 0;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__START_DATE = 1;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__END_DATE = 2;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getEmployee()
   * @generated
   */
  int EMPLOYEE = 6;

  /**
   * The feature id for the '<em><b>Employee Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__EMPLOYEE_ID = ROLE__EMPLOYEE_ID;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__START_DATE = ROLE__START_DATE;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__END_DATE = ROLE__END_DATE;

  /**
   * The feature id for the '<em><b>Availabilities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__AVAILABILITIES = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl <em>Manager</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getManager()
   * @generated
   */
  int MANAGER = 7;

  /**
   * The feature id for the '<em><b>Employee Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__EMPLOYEE_ID = ROLE__EMPLOYEE_ID;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__START_DATE = ROLE__START_DATE;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__END_DATE = ROLE__END_DATE;

  /**
   * The feature id for the '<em><b>Manages</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__MANAGES = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Manager</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.TaskImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTask()
   * @generated
   */
  int TASK = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ID = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ASSIGNMENT = 2;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TaskAssignmentImpl <em>Task Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.TaskAssignmentImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTaskAssignment()
   * @generated
   */
  int TASK_ASSIGNMENT = 9;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_ASSIGNMENT__ID = 0;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_ASSIGNMENT__ROLE = 1;

  /**
   * The feature id for the '<em><b>Availability</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_ASSIGNMENT__AVAILABILITY = 2;

  /**
   * The feature id for the '<em><b>Is Done</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_ASSIGNMENT__IS_DONE = 3;

  /**
   * The number of structural features of the '<em>Task Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_ASSIGNMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.AvailabilityImpl <em>Availability</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.warehouse.warehouseModelling.impl.AvailabilityImpl
   * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getAvailability()
   * @generated
   */
  int AVAILABILITY = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__ID = 0;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__START_TIME = 1;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__END_TIME = 2;

  /**
   * The number of structural features of the '<em>Availability</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.WarehouseManagement <em>Warehouse Management</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Warehouse Management</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.WarehouseManagement
   * @generated
   */
  EClass getWarehouseManagement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.WarehouseManagement#getCompanies <em>Companies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Companies</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.WarehouseManagement#getCompanies()
   * @see #getWarehouseManagement()
   * @generated
   */
  EReference getWarehouseManagement_Companies();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company
   * @generated
   */
  EClass getCompany();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Company#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getName()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Company#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getAddress()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Address();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Company#getWarehouses <em>Warehouses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Warehouses</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getWarehouses()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Warehouses();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Company#getTeams <em>Teams</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Teams</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getTeams()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Teams();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Company#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Company#getTasks()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Tasks();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse <em>Warehouse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Warehouse</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse
   * @generated
   */
  EClass getWarehouse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse#getName()
   * @see #getWarehouse()
   * @generated
   */
  EAttribute getWarehouse_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Warehouse#getWorkers <em>Workers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workers</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Warehouse#getWorkers()
   * @see #getWarehouse()
   * @generated
   */
  EReference getWarehouse_Workers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Team <em>Team</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Team</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Team
   * @generated
   */
  EClass getTeam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Team#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Team#getName()
   * @see #getTeam()
   * @generated
   */
  EAttribute getTeam_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Person#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Person#getRoles()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Roles();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Role#getEmployeeId <em>Employee Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Employee Id</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role#getEmployeeId()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_EmployeeId();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Role#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role#getStartDate()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_StartDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Role#getEndDate <em>End Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Date</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Role#getEndDate()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_EndDate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Employee
   * @generated
   */
  EClass getEmployee();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.warehouse.warehouseModelling.Employee#getAvailabilities <em>Availabilities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Availabilities</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Employee#getAvailabilities()
   * @see #getEmployee()
   * @generated
   */
  EReference getEmployee_Availabilities();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Manager <em>Manager</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Manager</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Manager
   * @generated
   */
  EClass getManager();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.warehouse.warehouseModelling.Manager#getManages <em>Manages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Manages</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Manager#getManages()
   * @see #getManager()
   * @generated
   */
  EReference getManager_Manages();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Task#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Task#getId()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Task#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Task#getDescription()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.warehouse.warehouseModelling.Task#getAssignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assignment</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Task#getAssignment()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Assignment();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.TaskAssignment <em>Task Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Assignment</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.TaskAssignment
   * @generated
   */
  EClass getTaskAssignment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getId()
   * @see #getTaskAssignment()
   * @generated
   */
  EAttribute getTaskAssignment_Id();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getRole()
   * @see #getTaskAssignment()
   * @generated
   */
  EReference getTaskAssignment_Role();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getAvailability <em>Availability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Availability</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.TaskAssignment#getAvailability()
   * @see #getTaskAssignment()
   * @generated
   */
  EReference getTaskAssignment_Availability();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.TaskAssignment#isIsDone <em>Is Done</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Done</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.TaskAssignment#isIsDone()
   * @see #getTaskAssignment()
   * @generated
   */
  EAttribute getTaskAssignment_IsDone();

  /**
   * Returns the meta object for class '{@link org.xtext.example.warehouse.warehouseModelling.Availability <em>Availability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Availability</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Availability
   * @generated
   */
  EClass getAvailability();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Availability#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Availability#getId()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Availability#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Availability#getStartTime()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.warehouse.warehouseModelling.Availability#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.warehouse.warehouseModelling.Availability#getEndTime()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_EndTime();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WarehouseModellingFactory getWarehouseModellingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl <em>Warehouse Management</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseManagementImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouseManagement()
     * @generated
     */
    EClass WAREHOUSE_MANAGEMENT = eINSTANCE.getWarehouseManagement();

    /**
     * The meta object literal for the '<em><b>Companies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE_MANAGEMENT__COMPANIES = eINSTANCE.getWarehouseManagement_Companies();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.CompanyImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getCompany()
     * @generated
     */
    EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__NAME = eINSTANCE.getCompany_Name();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__ADDRESS = eINSTANCE.getCompany_Address();

    /**
     * The meta object literal for the '<em><b>Warehouses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__WAREHOUSES = eINSTANCE.getCompany_Warehouses();

    /**
     * The meta object literal for the '<em><b>Teams</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__TEAMS = eINSTANCE.getCompany_Teams();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__TASKS = eINSTANCE.getCompany_Tasks();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl <em>Warehouse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getWarehouse()
     * @generated
     */
    EClass WAREHOUSE = eINSTANCE.getWarehouse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAREHOUSE__NAME = eINSTANCE.getWarehouse_Name();

    /**
     * The meta object literal for the '<em><b>Workers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE__WORKERS = eINSTANCE.getWarehouse_Workers();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl <em>Team</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.TeamImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTeam()
     * @generated
     */
    EClass TEAM = eINSTANCE.getTeam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEAM__NAME = eINSTANCE.getTeam_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.PersonImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__ROLES = eINSTANCE.getPerson_Roles();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.RoleImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Employee Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__EMPLOYEE_ID = eINSTANCE.getRole_EmployeeId();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__START_DATE = eINSTANCE.getRole_StartDate();

    /**
     * The meta object literal for the '<em><b>End Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__END_DATE = eINSTANCE.getRole_EndDate();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.EmployeeImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getEmployee()
     * @generated
     */
    EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '<em><b>Availabilities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMPLOYEE__AVAILABILITIES = eINSTANCE.getEmployee_Availabilities();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl <em>Manager</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.ManagerImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getManager()
     * @generated
     */
    EClass MANAGER = eINSTANCE.getManager();

    /**
     * The meta object literal for the '<em><b>Manages</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANAGER__MANAGES = eINSTANCE.getManager_Manages();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.TaskImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__ID = eINSTANCE.getTask_Id();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DESCRIPTION = eINSTANCE.getTask_Description();

    /**
     * The meta object literal for the '<em><b>Assignment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ASSIGNMENT = eINSTANCE.getTask_Assignment();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.TaskAssignmentImpl <em>Task Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.TaskAssignmentImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getTaskAssignment()
     * @generated
     */
    EClass TASK_ASSIGNMENT = eINSTANCE.getTaskAssignment();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_ASSIGNMENT__ID = eINSTANCE.getTaskAssignment_Id();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_ASSIGNMENT__ROLE = eINSTANCE.getTaskAssignment_Role();

    /**
     * The meta object literal for the '<em><b>Availability</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_ASSIGNMENT__AVAILABILITY = eINSTANCE.getTaskAssignment_Availability();

    /**
     * The meta object literal for the '<em><b>Is Done</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_ASSIGNMENT__IS_DONE = eINSTANCE.getTaskAssignment_IsDone();

    /**
     * The meta object literal for the '{@link org.xtext.example.warehouse.warehouseModelling.impl.AvailabilityImpl <em>Availability</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.warehouse.warehouseModelling.impl.AvailabilityImpl
     * @see org.xtext.example.warehouse.warehouseModelling.impl.WarehouseModellingPackageImpl#getAvailability()
     * @generated
     */
    EClass AVAILABILITY = eINSTANCE.getAvailability();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__ID = eINSTANCE.getAvailability_Id();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__START_TIME = eINSTANCE.getAvailability_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__END_TIME = eINSTANCE.getAvailability_EndTime();

  }

} //WarehouseModellingPackage
