/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WarehouseModellingUiModule extends AbstractWarehouseModellingUiModule {

	public WarehouseModellingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
