/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(WarehouseModellingInjectorProvider.class)
@SuppressWarnings("all")
public class WarehouseModellingParsingTest {
  @Inject
  private /* ParseHelper<WarehouseManagement> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field WarehouseModellingParsingTest.parseHelper refers to the missing type WarehouseManagement"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
