/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.warehouse.ui.internal.WarehouseActivator;

public class WarehouseModellingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WarehouseActivator.getInstance().getInjector("org.xtext.example.warehouse.WarehouseModelling");
	}

}
