/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.warehouse;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WarehouseModellingStandaloneSetup extends WarehouseModellingStandaloneSetupGenerated {

	public static void doSetup() {
		new WarehouseModellingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
