/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.wh.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.wh.ui.internal.WhActivator;

public class WHUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WhActivator.getInstance().getInjector("org.xtext.example.wh.WH");
	}

}
