/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.wh.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WHUiModule extends AbstractWHUiModule {

	public WHUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
